---
title: "Informe sobre Escovid19data"
author: "@numeroteca"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(formattable)
library(DT)
today <- as.Date("2020-05-21")
```

Un análisis automatizado de la base de datos por provincias de #COVID19 en España. Puedes acceder a todos los datos en el repositorio https://github.com/montera34/escovid19data

## Última fecha publicada 

```{r fecha0, fig.width=7, fig.height=4, echo=FALSE, warning=FALSE}
data_cases_sp_provinces <- readRDS(file = "../data/output/spain/covid19-provincias-spain_consolidated.rds")

fechas_caso <- data_cases_sp_provinces %>% group_by(province) %>% filter(!is.na(cases_accumulated) ) %>% top_n(1, date) %>% select(date, province,ccaa)
fechas_fallecidos <- data_cases_sp_provinces %>% group_by(province) %>% filter(!is.na(deceased) ) %>% top_n(1, date) %>% select(date, province,ccaa)
fechas_PCR_acum <- data_cases_sp_provinces %>% group_by(province) %>% filter(!is.na(cases_accumulated_PCR) ) %>% top_n(1, date) %>% select(date, province,ccaa)
fechas_PCR_diario <- data_cases_sp_provinces %>% group_by(province) %>% filter(!is.na(PCR) ) %>% top_n(1, date) %>% select(date, province,ccaa)
# 
# kable(fechas_caso %>% select(date, province,ccaa) %>% arrange(date), caption="Última fecha disponible de casos acumuados")
# kable(fechas_fallecidos  %>% select(date, province,ccaa) %>% arrange(date), caption="Última fecha disponible de fallecidos acumulados")
# kable(fechas_PCR_diario  %>% select(date, province,ccaa) %>% arrange(date), caption="Última fecha disponible de PCR positivo diario")

``` 

### Días desde que se tiene el último dato disponible desagregado por provincia:

NA indica valor no conocido.

```{r fecha1, fig.width=7, fig.height=15, echo=FALSE, warning=FALSE, error=FALSE }

table_total <- merge(
  fechas_caso %>% rename (casos_acum = date ) , 
  fechas_fallecidos %>% rename ( muertes_acum = date ) %>% select(-ccaa), 
  by.x="province", by.y="province", all = TRUE  )

table_total <- merge(
  table_total, 
  fechas_PCR_diario %>% rename ( PCR_diario = date ) %>% select(-ccaa), 
  by.x="province", by.y="province", all = TRUE  )

table_total <- merge(
  table_total, 
  fechas_PCR_acum %>% rename ( PCR_acum = date ) %>% select(-ccaa), 
  by.x="province", by.y="province", all = TRUE  )


# fort(table_total %>% select(province, ccaa, casos_acum, muertes_acum ) %>% 
#         mutate(
#           casos = today - casos_acum,
#           muertes = today - muertes_acum
#         ) %>%
#         mutate(
#           casos = as.integer(casos),
#           casos = color_bar("lightgreen")(casos)
#         ) %>%
#         select( province, ccaa, casos, casos_acum,  muertes, muertes_acum ) %>%
#         arrange(casos_acum), caption="Última fecha disponible según variable") %>%
#   kable_styling(bootstrap_options = c("hover", "condensed", "responsive"), fixed_thead = T)


table_nice <- table_total %>% 
        mutate(
          casos = as.integer( today - casos_acum ),
          muertes = as.integer( today - muertes_acum ),
          PCR =  as.integer( today - PCR_diario ),
          PCR_acum =  as.integer( today - PCR_acum )
        ) %>%
        select( province, ccaa, casos, casos_acum,  muertes, muertes_acum, PCR , PCR_acum) %>%
        arrange(casos_acum)

# formatter(style = x ~ style(..., display = ifelse(is.na(x), "none", "inline-block"))

as.datatable(
formattable(table_nice, list(
  area(col = c(casos, muertes,PCR, PCR_acum)) ~ normalize_bar("pink", 0.2,na.rm = TRUE)
)), colnames = c('Provincia', 'CCAA', 'Casos acumulado (días desde)', 'Casos (fecha)', 'Muertes acumulado (días desde)', 'Muertes (fecha)','PCR diario (días desde)', 'PCR acumulado (días desde)'  ),
options = list(pageLength = 52)
)
``` 

## Según fuentes de información

```{r todos1, fig.width=7, fig.height=4, echo=FALSE, warning=FALSE}

# data_cases_sp_provinces %>% filter(str_detect(source_name, ';')) %>% select(ccaa,source_name)

data_cases_sp_provinces  <- data_cases_sp_provinces %>% mutate (
  source_type = ifelse( str_detect(source_name, ';'),"mixta","única")
)
  # filter(str_detect(source_name, ';')) %>% select(ccaa,source_name)

lineas <- nrow(data_cases_sp_provinces)

data_cases_sp_provinces %>% group_by(source_type) %>% summarise( Freq = n()) %>%
ggplot( aes(x = reorder(source_type, Freq), y = Freq)) +
geom_col(fill = "grey") +
geom_text( aes(label = paste0(source_type, " (", format(round( Freq/lineas*100, digits = 1),decimal.mark = ","), "%)"), y = 50 ),
          hjust = 0,
          size=5,color="#000000",family = "Roboto Condensed") +
scale_y_continuous(labels=function(x) format(x, big.mark = ".", scientific = FALSE)) +
theme_minimal(base_family = "Roboto Condensed",base_size = 18) +
theme(
  # panel.grid.minor.x = element_blank(),
  # panel.grid.major.x = element_blank(),
  panel.grid.major.y = element_blank(),
  panel.grid.minor.y = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks.x = element_blank(),
  axis.ticks.y = element_blank()
  # legend.position = "bottom"
) +
labs(title = "Fuentes usadas por tipo en Escovid19data",
     subtitle = paste("Usa fuente de datos Mixtas o únicas. ",today,sep=""),
     y = "número de filas",
     x = "tipo",
     caption = paste0("Numero de filas:",lineas)
     ) +
coord_flip()

```

```{r todos2, fig.width=8, fig.height=12, echo=FALSE, warning=FALSE}
data_cases_sp_provinces <- readRDS(file = "../data/output/spain/covid19-provincias-spain_consolidated.rds")

lineas <- nrow(data_cases_sp_provinces)

fuentes <- as.data.frame(table(data_cases_sp_provinces$source_name))

fuentes <- fuentes %>% arrange(-Freq)

fuentes %>% arrange(-Freq) %>% head(50) %>%
ggplot( aes(x = reorder(Var1, Freq), y = Freq)) +
geom_col(fill = "grey") +
geom_text(aes(label = paste0(Freq, " (", format(round( Freq/lineas*100, digits = 1),decimal.mark = ","), "%) ", substr(Var1,1,70 )), y= 2 ),
          hjust = 0,
          size=5,color="#000000",family = "Roboto Condensed") +
scale_y_continuous(labels=function(x) format(x, big.mark = ".", scientific = FALSE)) +
theme_minimal(base_family = "Roboto Condensed",base_size = 18) +
theme(
  # panel.grid.minor.x = element_blank(),
  # panel.grid.major.x = element_blank(),
  panel.grid.major.y = element_blank(),
  panel.grid.minor.y = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks.x = element_blank(),
  axis.ticks.y = element_blank()
  # legend.position = "bottom"
) +
labs(title = "Fuentes usadas en Escovid19data",
     subtitle = paste("Veces que aparece cada fuente (% respecto total). ",today,sep=""),
     y = "Número de filas con esta fuente",
     x = "fuente",
     caption = paste0("Numero de filas:",lineas)
     ) +
coord_flip()

```



```{r rejillaccaa, fig.width=10, fig.height=13, echo=FALSE, warning=FALSE}
data_cases_sp_provinces <- readRDS(file = "../data/output/spain/covid19-provincias-spain_consolidated.rds")

fuentes <- data_cases_sp_provinces %>% group_by (ccaa,source_name) %>% summarise(
  Freq  = n()
) %>% rename ( Var1 = source_name )
# fuentes <- as.data.frame(table(data_cases_sp_provinces$source_name))

fuentes$Var1 <- as.factor(fuentes$Var1) 

fuentes %>% arrange(-Freq) %>% 
ggplot( aes(x = reorder(Var1, Freq), y = Freq)) +
geom_col(fill = "#DEDEDE", width = 2) +
geom_text(aes(label = paste0(Freq, " ", substr(Var1,1,70 )), y= 2 ),
          hjust = 0,
          size=3,color="#000000",family = "Roboto Condensed") +
# scale_y_continuous(labels=function(x) format(x, big.mark = ".", scientific = FALSE)) +
facet_wrap( ~ccaa, scales = "free_x") +
theme_minimal(base_family = "Roboto Condensed",base_size = 18) +
theme(
  panel.grid.minor.x = element_blank(),
  panel.grid.major.x = element_blank(),
  panel.grid.major.y = element_blank(),
  panel.grid.minor.y = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks.x = element_blank(),
  axis.ticks.y = element_blank()
  # legend.position = "bottom"
) +
labs(title = "Fuentes usadas en Escovid19data",
     subtitle = paste("Veces que aparece cada fuente (% respecto total. ", today, sep=""),
     y = "Número de filas con esta fuente",
     x = "fuente",
     caption = paste0("Numero de filas:",lineas)
     ) +
coord_flip()
```

```{r casos, fig.width=8, fig.height=12, echo=FALSE, warning=FALSE}
data_cases_sp_provinces <- readRDS(file = "../data/output/spain/covid19-provincias-spain_consolidated.rds")

data_cases_sp_provinces <- data_cases_sp_provinces %>% filter( !is.na(cases_accumulated) )

lineas <- nrow(data_cases_sp_provinces)

fuentes <- as.data.frame(table(data_cases_sp_provinces$source_name))

fuentes <- fuentes %>% arrange(-Freq)

fuentes %>% arrange(-Freq) %>% head(50) %>%
ggplot( aes(x = reorder(Var1, Freq), y = Freq)) +
  geom_col(fill = "grey") +
  geom_text(aes(label = paste0(Freq, " (", format(round( Freq/lineas*100, digits = 1),decimal.mark = ","), "%) ", substr(Var1,1,70 )), y= 2 ),
            hjust = 0,
            size=5,color="#000000",family = "Roboto Condensed") +
  scale_y_continuous(labels=function(x) format(x, big.mark = ".", scientific = FALSE)) +
  theme_minimal(base_family = "Roboto Condensed",base_size = 18) +
  theme(
    # panel.grid.minor.x = element_blank(),
    # panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank()
    # legend.position = "bottom"
  ) +
  labs(title = "Fuentes usadas en Escovid19data. Datos de casos",
       subtitle = paste("Veces que aparece cada fuente (% respecto total). ",today,sep=""),
     y = "Número de filas con esta fuente",
     x = "fuente",
       caption = paste0("Numero de filas:",lineas)
       ) +
  coord_flip()
```

```{r muertes, fig.width=8, fig.height=12, echo=FALSE, warning=FALSE}
data_cases_sp_provinces <- readRDS(file = "../data/output/spain/covid19-provincias-spain_consolidated.rds")

data_cases_sp_provinces <- data_cases_sp_provinces %>% filter( !is.na(deceased) )

lineas <- nrow(data_cases_sp_provinces)

fuentes <- as.data.frame(table(data_cases_sp_provinces$source_name))

fuentes <- fuentes %>% arrange(-Freq)

fuentes %>% arrange(-Freq) %>% head(50) %>%
ggplot( aes(x = reorder(Var1, Freq), y = Freq)) +
  geom_col(fill = "grey") +
  geom_text(aes(label = paste0(Freq, " (", format(round( Freq/lineas*100, digits = 1),decimal.mark = ","), "%) ", substr(Var1,1,70 )), y= 2 ),
            hjust = 0,
            size=5,color="#000000",family = "Roboto Condensed") +
  scale_y_continuous(labels=function(x) format(x, big.mark = ".", scientific = FALSE)) +
  theme_minimal(base_family = "Roboto Condensed",base_size = 18) +
  theme(
    # panel.grid.minor.x = element_blank(),
    # panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank()
    # legend.position = "bottom"
  ) +
  labs(title = "Fuentes usadas en Escovid19data. Datos de fallecidos",
       subtitle = paste("Veces que aparece cada fuente (% respecto total)",sep=""),
       # y = "Número de tuits con esa URL",
       # x = "",
       caption = paste0("Numero de filas:",lineas)
       ) +
  coord_flip()
```
